[workspace]
members = ["replay", "tools", "profiler-sdk", "state-reader"]


# Explicitly set the resolver to the default for edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.dependencies]
starknet-types-core = "0.2.0"
tracing = "0.1"
serde_json = "1.0.135"
serde_with = "3.12.0"
serde = "1.0.219"
fs2 = "0.4.3"
cairo-native = { git = "https://github.com/lambdaclass/cairo_native", rev = "b3fea26c8a3f3a48d0f1b473d7439435c6389083" }
cairo-vm = "3.1.0"
anyhow = "1.0"

# Cairo Dependencies
cairo-lang-filesystem = "~2.16.0"
cairo-lang-starknet-classes = "~2.16.0"
cairo-lang-starknet = "~2.16.0"
cairo-lang-compiler = "~2.16.0"
cairo-lang-sierra = "~2.16.0"

# Sequencer Dependencies
starknet_api = { git = "https://github.com/lambdaclass/sequencer.git", rev = "594e2e2a1d5258c4310b77796f42b39ef567523f" } # update_native
blockifier = { git = "https://github.com/lambdaclass/sequencer.git", rev = "594e2e2a1d5258c4310b77796f42b39ef567523f", features = [ "cairo_native", ] } # update_native
blockifier_reexecution = { git = "https://github.com/lambdaclass/sequencer.git", rev = "594e2e2a1d5258c4310b77796f42b39ef567523f" } # update_native

[patch.crates-io]
cairo-vm = { git = "https://github.com/avivg-starkware/cairo-vm", rev = "2ad6d5fba6df67da62309bb64d1482a47ad54132" }
