[workspace]
members = ["replay", "tools", "profiler-sdk", "state-reader"]


# Explicitly set the resolver to the default for edition >= 2021
# https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html
resolver = "2"

[workspace.dependencies]
starknet-types-core = "0.2.0"
tracing = "0.1"
serde_json = "1.0.135"
serde_with = "3.12.0"
serde = "1.0.219"
fs2 = "0.4.3"
cairo-native = "0.9.0-rc.5"
cairo-vm = "3.2.0"
anyhow = "1.0"

# Cairo Dependencies
cairo-lang-filesystem = "~2.17.0-rc.4"
cairo-lang-starknet-classes = "~2.17.0-rc.4"
cairo-lang-starknet = "~2.17.0-rc.4"
cairo-lang-compiler = "~2.17.0-rc.4"
cairo-lang-sierra = "~2.17.0-rc.4"

# Sequencer Dependencies
starknet_api = { git = "https://github.com/starkware-libs/sequencer.git", rev = "c9f42dd9c3e1bdf4f35949a22ef13dcc37e65755" }
blockifier = { git = "https://github.com/starkware-libs/sequencer.git", rev = "c9f42dd9c3e1bdf4f35949a22ef13dcc37e65755", features = [ "cairo_native", "benchmarking", "transaction_serde" ] }
blockifier_reexecution = { git = "https://github.com/starkware-libs/sequencer.git", rev = "c9f42dd9c3e1bdf4f35949a22ef13dcc37e65755" }
