[package]
name = "profiler-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
serde_json = "1.0.140"
regex = "1.11.1"
itertools = "0.14.0"
