[package]
name = "rpc-state-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = { version = "2.7.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = [
    "arbitrary_precision",
    "raw_value",
] }
starknet_api = "=0.12.0-dev.1"
cairo-lang-starknet = "=2.6.3"
cairo-lang-starknet-classes = "=2.6.3"
cairo-lang-utils = "=2.6.3"
starknet = "0.7.0" 
thiserror = { workspace = true }
flate2 = "1.0.25"
serde_with = "3.0.0"
dotenv = "0.15.0"
cairo-vm = "0.9.2"
blockifier = { git = "https://github.com/NethermindEth/blockifier", rev = "3844200855dab89ea24f80588c21edb065401123" }


[dev-dependencies]
pretty_assertions_sorted = "1.2.3"
test-case = "3.1.0"
