[package]
name = "rpc-state-reader"
version = "0.1.0"
edition = "2021"

[features]
# The only_casm feature compiles all the Sierra fetched contracts to CASM.
# We use this feature to avoid using cairo_native in the Replay crate.
only_casm = []

[dependencies]
ureq = { version = "2.7.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = [
  "arbitrary_precision",
  "raw_value",
] }
starknet_api = {workspace = true}
cairo-lang-starknet = "2.7.0"
cairo-lang-sierra = "2.7.0"
cairo-lang-starknet-classes = "2.7.0"
cairo-lang-utils = "2.7.0"
cairo-native = { git = "https://github.com/lambdaclass/cairo_native", branch = "cairo-lang2.7.0-rc.3" }
starknet = "0.7.0"
thiserror = { workspace = true }
flate2 = "1.0.25"
dotenv = "0.15.0"
cairo-vm = "1.0.0-rc5"
blockifier = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions_sorted = "1.2.3"
test-case = "3.1.0"
