[package]
name = "replay"
version = "0.1.0"
edition = "2021"

[features]
benchmark = []
# The only_cairo_vm feature is designed to avoid executing transitions with cairo_native and instead use cairo_vm exclusively
only_cairo_vm = ["rpc-state-reader/only_casm"]

[dependencies]
# starknet specific crates
blockifier = { workspace = true }
rpc-state-reader = { path = "../rpc-state-reader" }
starknet_api = { workspace = true }
# CLI specific crates
clap = { version = "4.4.6", features = ["derive"] }
# logs
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
# error handling
anyhow = "1.0"
cairo-vm = "0.9.3"
