[workspace]

[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[dependencies]

cairo-lang-starknet-classes = "2.12.0-dev.0"
cairo-lang-starknet = "2.12.0-dev.0"
cairo-lang-compiler = "2.12.0-dev.0"
serde_json = "1.0.135"
