name: Daily Block Run

on:
  schedule:
  # At the end of every day
  - cron: "0 0 * * *"
  # remove later, only for testing
  push:

env:
  RANGE_SIZE: 1

jobs:
  run-and-compare:
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    env:
      LLVM_SYS_191_PREFIX: /usr/lib/llvm-19/
      MLIR_SYS_190_PREFIX: /usr/lib/llvm-19/
      TABLEGEN_190_PREFIX: /usr/lib/llvm-19/
      RPC_ENDPOINT_TESTNET: ${{ secrets.RPC_ENDPOINT_TESTNET }}
      RPC_ENDPOINT_MAINNET: ${{ secrets.RPC_ENDPOINT_MAINNET }}
    strategy:
      matrix:
        block:
          - 740000
          - 741000
          - 742000
          - 743000
          - 744000
          - 745000
          - 746000
          - 747000
          - 748000
          - 749000
          # remove later, only for testing
          - 803072

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install-linux-deps
      - name: Setup rust env
        uses: dtolnay/rust-toolchain@1.80.0
      - name: Retreive cached dependecies
        uses: Swatinem/rust-cache@v2
      - uses: ./.github/actions/install-native-runtime
      - name: Run with Native
        run: |
          BLOCK_START=${{ matrix.block }}
          BLOCK_END=$(($BLOCK_START + $RANGE_SIZE - 1))
          cargo run --release --features state_dump block-range $BLOCK_START $BLOCK_END mainnet
      - name: Run with VM
        run: |
          BLOCK_START=${{ matrix.block }}
          BLOCK_END=$(($BLOCK_START + $RANGE_SIZE - 1))
          cargo run --release --features state_dump,only_cairo_vm block-range $BLOCK_START $BLOCK_END mainnet
      - name: Compare states
        run: ./scripts/cmp_state_dumps.sh
  
